#!/bin/sh

# Random hexadecimal generator
# The first argument is the number of random bits to output. The second
# argument is the number of iterations to perform.

n_bits=${1:-128}
n_bytes=$(expr "$n_bits" / 8)
lines=${2:-1}

i=0
while test $i -lt $lines
do
	od -An -vtx1 -N$n_bytes /dev/urandom \
	| tr -d '\n '
	printf "\n"
	i=$((i+1))
done
